[package]
name = "plonk-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
ff = "0.12.0"
group = "0.12.0"
lazy_static = "1.4.0"

# halo2
halo2_proofs = { version = "0.1.0", optional = true }
blake2b_simd = { version = "1.0.0", optional = true }

[dev-dependencies]
rand = "0.8"

[features]
default = ["halo2"]
halo2 = ["dep:halo2_proofs", "dep:blake2b_simd"]

[patch.crates-io]
halo2_proofs = { git = "https://github.com/han0110/halo2", branch = "feature/abstraction-experiment", package = "halo2_proofs" }
