[package]
name = "plonk-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
ff = "0.12.0"
group = "0.12.0"
lazy_static = "1.4.0"

# halo2
halo2_proofs = { version = "0.1.0", optional = true }
blake2b_simd = { version = "1.0.0", optional = true }

# evm
ethereum_types = { package = "ethereum-types", version = "0.13.1", default-features = false, features = ["std"], optional = true }
foundry_evm = { git = "https://github.com/foundry-rs/foundry", package = "foundry-evm", optional = true }
crossterm = { version = "0.22.1", optional = true }
tui = { version = "0.16.0", default-features = false, features = ["crossterm"], optional = true }

[dev-dependencies]
rand = "0.8"

[features]
default = ["halo2", "evm"]
halo2 = ["dep:halo2_proofs", "dep:blake2b_simd"]
evm = ["dep:foundry_evm", "dep:crossterm", "dep:tui", "dep:ethereum_types"]

[patch.crates-io]
halo2_proofs = { git = "https://github.com/han0110/halo2", branch = "feature/abstraction-experiment", package = "halo2_proofs" }
